# Generated by Django 6.0.4 on 2026-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('national', 'National Holiday'), ('festival', 'Festival Holiday'), ('hostel', 'Hostel Holiday'), ('emergency', 'Emergency Holiday')], max_length=20),
        ),
    ]
