# Generated by Django 6.0.4 on 2026-06-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
